#!/bin/bash

ORACLE_BASE=/u01/app/oracle
export ORACLE_BASE

ORACLE_SID=ORCL
export ORACLE_SID

ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1
export ORACLE_HOME

PATH=$ORACLE_HOME/bin:$PATH
export PATH

mount -t tmpfs shmfs -o size=4g /dev/shm

while true; do
  status=`ps -ef | grep tns | grep oracle`
  pmon=`ps -ef | egrep pmon_$ORACLE_SID'\>' | grep -v grep`
  if [ "$status" == "" ] || [ "$pmon" == "" ]
  then
    su -s /bin/bash oracle -c "lsnrctl start"
    su -s /bin/bash oracle -c "sqlplus /nolog @?/config/scripts/startdb.sql"
    su -s /bin/bash oracle -c "lsnrctl status"
  fi
  sleep 1m
done;
